## **Task 13 Solution** ##


**Question 1**
- Create a 6x6 NumPy array with random integers between 1 and 50. 
- Display the array.

In [1]:

# importing numpy library
import numpy as np

# method 2 to generate random integer numbers
rng = np.random.default_rng()

# printing random integer numbers using random and randint
arr_6 = np.random.randint(1,50, [6, 6])

# printing the 6x6 numpy array
print("A 6x6 Numpy Array\n", arr_6)
rng.integers(1,51, size=(6, 6))




A 6x6 Numpy Array
 [[10 30 42 40 45 18]
 [24 20  8 30 33 19]
 [40 28 45  5 30 24]
 [22 39 14 19  1 14]
 [38 27 26 34 46 13]
 [43 36 33 16  8 42]]


array([[14, 25,  3,  2, 32, 11],
       [12, 29, 30, 15, 48, 22],
       [ 1,  7, 35, 18, 13,  8],
       [43, 10, 37, 40, 46, 43],
       [ 9, 47, 31,  3,  7, 45],
       [31, 38, 34,  2, 29, 20]])

**Question 2**
Extract the following from the array you created in Question 1: 
- The first two rows. 
- The last three columns. 
- All even numbers in the array.

In [2]:

# Extracting the first two rows
print("First two rows in the array\n" , arr_6[0:2])

# Extracting the last three columns
print("The last three columns in the array\n" , arr_6[:, 3:])

# Extracting all even numbers in the array
even_arrays = arr_6[arr_6%2 == 0]
print("This is the list of even numbers within the array\n", even_arrays)


First two rows in the array
 [[10 30 42 40 45 18]
 [24 20  8 30 33 19]]
The last three columns in the array
 [[40 45 18]
 [30 33 19]
 [ 5 30 24]
 [19  1 14]
 [34 46 13]
 [16  8 42]]
This is the list of even numbers within the array
 [10 30 42 40 18 24 20  8 30 40 28 30 24 22 14 14 38 26 34 46 36 16  8 42]


**Question 3**
 Perform the following array transformations:
- Reshape the array into a 3D (3, 2, 6) array. 
-  Flatten the reshaped array back to 1D.


In [3]:

# Reshaping the array to a 3D array
reshape_3d = arr_6.reshape(3,2,6)
print("Reshaped to 3x2x6: \n\n", reshape_3d)

#  Flatten the reshaped array back to 1D.
flattened = reshape_3d.flatten()
print("\nFlattened the reshaped array back to 1D\n", flattened)

Reshaped to 3x2x6: 

 [[[10 30 42 40 45 18]
  [24 20  8 30 33 19]]

 [[40 28 45  5 30 24]
  [22 39 14 19  1 14]]

 [[38 27 26 34 46 13]
  [43 36 33 16  8 42]]]

Flattened the reshaped array back to 1D
 [10 30 42 40 45 18 24 20  8 30 33 19 40 28 45  5 30 24 22 39 14 19  1 14
 38 27 26 34 46 13 43 36 33 16  8 42]


**Question 4**
-  Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [4]:
# generating a 4x4 identity matrix
identity_matrix = np.eye(4)

# setting values to replace the identity matrix diagonal
diagonal_numbers = np.arange(10, 41,10)

# setting the identity diagonal numbers
np.fill_diagonal(identity_matrix, diagonal_numbers)

# displaying the matrix
print(identity_matrix)



[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


**Question 5**
- Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [5]:
# A 3x4 matrix of random integers
matrix1 = np.random.randint(1,11, [3, 4])
print("A 3x4 matrix\n", matrix1)

# A 4x3 matrix of random integers
matrix2 = np.random.randint(1,11, [4, 3])
print("A 4x3 matrix\n", matrix2)

# Reshaping matrix2 array to a 3x4 array
reshaped_array = matrix2.reshape(3,4)
print("Reshaped to 3x4: \n\n", reshaped_array)

# multiplying the matrix
multiplied_array = matrix1 * reshaped_array

# printing output
print("This multiplies matrix1 by matrix2: \n\n", multiplied_array)


A 3x4 matrix
 [[1 6 7 7]
 [8 8 3 7]
 [3 1 3 3]]
A 4x3 matrix
 [[ 8  6  5]
 [ 3  2  3]
 [ 9  4  8]
 [10  8  7]]
Reshaped to 3x4: 

 [[ 8  6  5  3]
 [ 2  3  9  4]
 [ 8 10  8  7]]
This multiplies matrix1 by matrix2: 

 [[ 8 36 35 21]
 [16 24 27 28]
 [24 10 24 21]]


**Question 6**
-  Create a function that takes a 2D NumPy array as input and returns a new array where:
-  All even numbers are squared. 
- All odd numbers are replaced by -1.

In [6]:
# function to create the 2D numpy array
def array_input():
   
    print("Performing operations on 2D NumPy array")
    
    # taking number of row inputs
    array_rows= np.array(int(input("Enter number of rows for the 2D array: ")))

    # taking number of columns input
    array_cols= np.array(int(input("Enter number of columns for the 2D array: ")))

    # shaping the 2D array and putting the range of numbers
    array_2d = np.arange(array_cols * array_rows).reshape(array_rows, array_cols)

    # Ensuring all even numbers are squared and all odd numbers are replaced by -1.
    new_array = np.where(array_2d % 2 == 0, array_2d**2, -1)
    
    # returning the 2D array
    return new_array

# printing the function
print(array_input())



Performing operations on 2D NumPy array
[[  0  -1   4  -1  16  -1]
 [ 36  -1  64  -1 100  -1]
 [144  -1 196  -1 256  -1]
 [324  -1 400  -1 484  -1]
 [576  -1 676  -1 784  -1]]
